name: 52 Portraits
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a5efd2b-3b25-4009-ae1d-05c217474fa0.jpg
layout_spectrum: 1
typography_spectrum: 0.3749507248867303
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/141d6fd8-2c0b-4463-a760-de185857f3ee.png
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a1b7cbd-40ff-4189-8bf7-ff5e7225c42e.jpg
  type: null
  appId: null
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.11577716772444546
purpose: []
